### ISSUE TITLE
Adding attendee phone number should show format prior to entry

### ISSUE THREAD

**Issue by GovInTrenches** [OpenTechStrategies/streetcrm#260] opened 2015-10-28 12:32 UTC
http://swoptact.opentechstrategies.com/swoptact/event/16/?_changelist_filters=tags__name%3Dall 

Entering phone number doesn't specify format initially. When entering a phone number in the wrong format it prompts for a correction.

**Comment by GovInTrenches** [comment] 2015-10-28 15:27
![image](https://cloud.githubusercontent.com/assets/1302753/10793316/5eacd980-7d5e-11e5-9fdc-4c0a6d4432f7.png)
 
I updated the phone number, but it's still showing an error. I had to reload the page to get it to take.

**Comment by cecilia-donnelly** [comment] 2015-10-28 19:30
I'm really glad you opened this!  The actual issue is that we aren't showing the correct error(s) for phone numbers.  We don't really care about the phone number format.  The error is coming up in the example above because "555" is not a real area code, so the phone number isn't valid.  Another error might appear if you only entered 7 digits of the phone number, with no area code.  This is definitely a key issue, though.

Thanks!

**Comment by cecilia-donnelly** [comment] 2015-10-28 19:31
(See also a mention of this in #200.)

**Comment by GovInTrenches** [comment] 2015-10-28 19:31
Oh snap, I didn't realize that 555 could do that!

**Comment by cecilia-donnelly** [comment] 2015-10-28 19:33
Well, the error should clue you in anyway. :)  Better that you didn't know!!

**Comment by cecilia-donnelly** [comment] 2017-06-09 21:21
Closing as a duplicate of #187, but this has some useful information about the errors that will remain relevant.

**Closed by cecilia-donnelly** 2017-06-09 21:21 UTC
